#!/usr/bin/python3.5
# EASY-INSTALL-ENTRY-SCRIPT: 'salt==3003.3','console_scripts','salt-call'
__requires__ = 'salt==3004'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('salt==3004', 'console_scripts', 'salt-call')()
    )
